version: '3'
services:
  app:
    container_name: "app"
    build: .
    ports:
      - 8000:80
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
    - 27017:27017
    volumes:
      - .data :/data/db